# Generated by Django 3.2.16 on 2024-11-18 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='date',
        ),
        migrations.AddField(
            model_name='orders',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='Дата завершения'),
        ),
        migrations.AddField(
            model_name='orders',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
