# Generated by Django 3.2.16 on 2024-11-18 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_auto_20241118_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='end',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
